### ISSUE TITLE
Custom Task Jingle Not Working. 

### ISSUE THREAD

**Issue by MACHlNlST** [maximonster/TaskJingle#10]
Maybe the instructions are unclear but when I try to make a custom task jingle with my own mp3 file it just plays the default track instead. The file is located on my desktop and it just doesn't work, please help.
![asdasdasdasd](https://github.com/user-attachments/assets/d993805e-f74e-492b-9252-e27c4010c582)

**Comment by maximonster** [comment]
The file name in your path seems to be incorrect. It should also include the extension ".mp3".

Try entering C:\Users\druid\Desktop\taskjingle.mp3

**Comment by MACHlNlST** [comment]
That solved it thanks!
