### ISSUE TITLE
Custom sound option

### ISSUE THREAD

**Issue by mike-ul** [maximonster/TaskJingle#2]
Getting an option to specify the location of a mp3 file on your system to use as the jingle.

**Comment by maximonster** [comment]
Added in update

**Comment by jack8737** [comment]
Am i misusing the plugin? I tried uploading a soundclip to YouTube and SoundCloud but neither have worked. I also tried pasting the local path to the file saved on my PC. The Custom Jingle button was selected but the only thing it does is make the default jingle sound louder. Sorry if I am using it incorrectly.

**Comment by maximonster** [comment]
For the path on your pc make sure it's the complete path including the drive. For using a website the link needs to end in .MP3 and actually link to the file directly

**Comment by jack8737** [comment]
> 

Thanks for the response! Actually fixed it just by moving it from my Music folder to my Desktop. For some reason my PC was asking for permission to access the folder. Great plugin. Thx!\
