### ISSUE TITLE
Feature Suggestion: Toggleable Quest Complete Jingle

### ISSUE THREAD

**Issue by Mr-Sisyphus** [maximonster/TaskJingle#3]
the ability to toggle the jingle to play upon quest completion would be cool, definitely fits thematically with the "Mission passed" default jingle as quests are more akin to missions than slayer tasks (in my opinion atleast)

**Comment by maximonster** [comment]
Probably would work better as a separate plugin. Also would be somewhat annoying to test due to quests only being completable once
