### ISSUE TITLE
Custom Jingle from URL Does Not Function Correctly

### ISSUE THREAD

**Issue by NoahTingey** [maximonster/TaskJingle#4]
I copy/pasted this url into the "Custom path" field of the plugin settings:
`https://www.myinstants.com/media/sounds/gta-san-andreas-mission-complete-sound-hq_4ZVTov6.mp3`

And my "Custom Jingle" option is checked. However, when I complete a slayer task I do not hear the jingle. 

Downloading the same jingle and then typing the file path into "Custom path" works fine, though.

**Comment by maximonster** [comment]
Working properly in newest version
