### ISSUE TITLE
!testjingle and !testlvljingle are being used to troll other players

### ISSUE THREAD

**Issue by Naguanil** [maximonster/TaskJingle#9]
The commends !testjingle and !testlvljingle can be typed in-game and both currently force the client to play either jingle for everyone who sees the message who has the client installed, at 100% volume even if  you have them turned down. Please consider adjusting this somehow so it can't be used nefariously (I have evil friends)

**Comment by Felanbird** [comment]
These commands can just be dropped down to `::` commands, see https://oldschool.runescape.wiki/w/Chat_Interface#Commands & https://static.runelite.net/api/runelite-api/net/runelite/api/events/CommandExecuted.html

**Comment by maximonster** [comment]
Fixed in latest commit, thanks for letting me know and thanks Felanbiard for the resources.
